spring.application.name=BTGPactual

spring.datasource.url=jdbc:mysql://localhost:3306/BTGPactual_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA/Hibernate para Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto de la aplicación (dentro del contenedor)
server.port=8085

# Logging
logging.pattern.console=[%thread] %-5level:%logger - %msg%n
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
spring.main.banner-mode=off